export const ROUTES = {
  HOME: '/',
  CART: '/cart',
  PRODUCT: '/products/:slug',
  MIGRATION_HOME: '/migration',
  MIGRATION_ASSESS: '/migration/:platform',
  MIGRATION_PHASE: '/migration/:platform/:phase',
  ROM_CALCULATOR: '/migration/calculator',
  AI_FACTORY: '/content/ai-factory',
  WHITEPAPER: '/content/:slug',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/account',
  DOWNLOADS: '/account/downloads',
  DEPLOYMENTS: '/account/deployments',
  ORDERS: '/account/orders',
  WISHLIST: '/account/wishlist',
  SETTINGS: '/account/settings',
  DATABRICKS_CALLBACK: '/auth/databricks/callback',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_ORDERS: '/admin/orders',
  ROM_ADMIN: '/admin/rom-config',
} as const;
