export const EVENTS = {
  PAGE_VIEW: '$pageview',
  PAGE_TAGGED: 'page_tagged',
  NAV_CLICK: 'nav_link_clicked',
  BPCS_LINK_CLICKED: 'bpcs_link_clicked',
  CATEGORY_FILTERED: 'category_filtered',
  PRODUCT_CARD_CLICKED: 'product_card_clicked',
  PRODUCT_CARD_VISIBLE: 'product_card_visible',
  PRODUCT_MODAL_OPENED: 'product_modal_opened',
  PRODUCT_MODAL_TAB: 'product_modal_tab_changed',
  PRODUCT_PAGE_VIEWED: 'product_page_viewed',
  VIDEO_PLAYED: 'video_played',
  VIDEO_PROGRESS: 'video_progress',
  SCROLL_DEPTH: 'scroll_depth',
  CART_ITEM_ADDED: 'cart_item_added',
  CART_ITEM_REMOVED: 'cart_item_removed',
  CART_VIEWED: 'cart_viewed',
  CHECKOUT_STARTED: 'checkout_started',
  CHECKOUT_COMPLETED: 'checkout_completed',
  MIGRATION_STARTED: 'migration_assessment_started',
  MIGRATION_SECTION_COMPLETED: 'migration_section_completed',
  MIGRATION_ROM_GENERATED: 'migration_rom_generated',
  LOGIN_COMPLETED: 'login_completed',
  SIGNUP_COMPLETED: 'signup_completed',
  SESSION_TIMEOUT: 'session_expired',
  CONTACT_FORM_SUBMITTED: 'contact_form_submitted',
  MODAL_INTERACTION: 'modal_interaction',
  FORM_ABANDONED: 'form_abandoned',
  CTA_CLICKED: 'cta_clicked',
  TIME_ON_PAGE: 'time_on_page',
  CHAT_OPENED: 'chat_opened',
  CHAT_MESSAGE_SENT: 'chat_message_sent',
  DOWNLOAD_INITIATED: 'download_initiated',
  DOWNLOAD_COMPLETED: 'download_completed',
  DEPLOY_INITIATED: 'deploy_initiated',
  DEPLOY_COMPLETED: 'deploy_completed',
  MEGA_MENU_OPENED: 'mega_menu_opened',
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
